# 基本設置
site_name: DaWei
site_url: https://dwhao84.github.io/
site_author: DaWei
site_description: Portfolio website for DaWei

# 主題設置
theme:
  name: material
  language: zh-Hant

  # 樣式設定
  logo: assets/logo.png
  favicon: assets/square-code.png

  # 配色設定
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  # 功能設定
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

# 插件設定
plugins:
  - search:
      lang:
        - en
        - zh
  - tags
  - redirects:
      redirect_maps:
        index.md: zh-Hant/index.md

# 擴展設定
markdown_extensions:
  - tables
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg # 導覽設定

nav:
  - Home: index.md
  - About:
      - 中文: zh-Hant/index.md
      - English: en/index.md
  - Projects:
      - 中文: zh-Hant/專案.md
      - English: en/projects.md
  - Tech Stack:
      - 中文: zh-Hant/技術.md
      - English: en/techstack.md
  - Experience:
      - 中文: zh-Hant/工作經驗.md
      - English: en/resume.md
  - Contact:
      - 中文: zh-Hant/聯絡方式.md
      - English: en/contact.md

# 額外設定
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dwhao84
    - icon: fontawesome/brands/medium
      link: https://medium.com/@dwsamurai84_dev
    - icon: fontawesome/solid/envelope
      link: mailto:dwsamurai84@gmail.com

# 版權設定
copyright: Copyright &copy; 2024 DaWei

# CSS 自定義
extra_css:
  - assets/extra.css
