# 基本設置
site_name: Da-Wei
site_url: https://dwhao84.github.io/
site_author: Da-Wei
site_description: Personal documentation and notes

# 主題設置
theme:
  name: material
  language: zh-Hant # 改為 zh，而不是 zh-TW
  logo: assets/logo.png

  # 功能設定
  features:
    # 導航功能
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - toc.follow

    # 搜尋功能
    - search.highlight
    - search.share
    - search.suggest

    # 內容功能
    - content.code.copy
    - content.tabs.link

  # 配色方案
  palette:
    # 亮色主題
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: 切換至深色模式

    # 暗色主題
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: purple
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: 切換至淺色模式

# 社群連結
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dwhao84
      name: GitHub
    - icon: fontawesome/brands/medium
      link: https://medium.com/@dwsamurai84_dev
      name: Medium
    - icon: fontawesome/solid/envelope
      link: mailto:dwsamurai84@gmail.com
      name: Email

# 頁腳設定
copyright: Copyright &copy; 2024 Da-Wei

# 導航設置
nav:
  - 首頁 / Home:
      - 歡迎: index.md
  - 筆記 / Notes:
      - Swift: tutorials/swift.md
      - Python: tutorials/python.md
  - 關於我 / About Me: about.md
  - 聯絡方式 / Contact: contact.md

# Markdown 擴展
markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

# 插件 (簡化版)
plugins:
  - search
