name: MkDocs Build & Deploy

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - run: pip install mkdocs-material

    - run: python scripts/generate_index.py

    - run: python scripts/generate_projects.py

    - run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        mkdocs gh-deploy --force
